on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
name: Continuous Integration
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Test
      run: |
        make test-full -B
    - name: Lint
      if: success() && matrix.platform == 'ubuntu-latest' && matrix.go-version == '1.13.x'
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        go get -u golang.org/x/lint/golint
        GOLINT_PATH=$(go list -f {{.Target}} golang.org/x/lint/golint)
        export PATH=$PATH:${GOLINT_PATH}
        make lint -B
    - name: Upload Coverage
      if: success() && matrix.platform == 'ubuntu-latest' && matrix.go-version == '1.13.x'
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
      run: |
        make coverage -B
        bash <(curl -s https://codecov.io/bash) -f coverage/output/coverage.txt
